services:
  charts:
    build:
      context: ./service/charts
      dockerfile: Dockerfile
    container_name: charts
    ports:
      - "8082:8080"

  api:
    build:
      context: ./service/api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8081:8080"
    environment:
      OGD_CHART_SERVICE_ENDPOINT: "http://charts:8080"
    depends_on:
      - charts
