FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
RUN mkdir -p service/charts
COPY ./*.py ./service/charts

ENV OGD_BASE_DIR=/app/efs

CMD ["python3", "-m", "service.charts.ogd"]
