# All parameters, generated using
#
# df = db.read_parameters(conn)
# xs = list(s.to_dict() for _, s in df.iterrows())
# {x['shortname']: x for x in xs}
#

_COMMENT = """
Units we care about:

* Böenspitze (Sekundenböe) (fkl010d1)
* Luftdruck auf Barometerhöhe (QFE) (prestad0)
* Lufttemperatur 2 m über Boden (tre200d0)
* Niederschlag (rre150d0)
* Relative Luftfeuchtigkeit 2 m über Boden (ure200d0)
* Sonnenscheindauer (sre000d0)
* Windgeschwindigkeit skalar (fkl010d0)
* Windrichtung (dkl010d0)


Frequency of columns in historical daily data:

[(4422732, 'rre150d0_count'),
 (3186651, 'tre200d0_count'),
 (2853791, 'fkl010d0_count'),
 (2729305, 'fu3010d0_count'),
 (2727246, 'ure200d0_count'),
 (2707578, 'tre200dn_count'),
 (2697903, 'pva200d0_count'),
 (2510862, 'tre200dx_count'),
 (2492608, 'prestad0_count'),
 (1871335, 'sre000d0_count'),
 (1800136, 'xno012d0_count'),
 (1772228, 'sremaxdv_count'),
 (1739472, 'fkl010d1_count'),
 (1733950, 'fu3010d1_count'),
 (1648405, 'dkl010d0_count'),
 (1599862, 'xno000d0_count'),
 (1576664, 'xcd000d0_count'),
 (1369920, 'rka150d0_count'),
 (1338734, 'gre000d0_count'),
 (1260676, 'erefaod0_count'),
 (1057259, 'rreetsd0_count'),
 (959349, 'tre005dn_count'),
 (919718, 'tre005dx_count'),
 (919698, 'tre005d0_count'),
 (858720, 'pp0qnhd0_count'),
 (785932, 'fkl010d3_count'),
 (784651, 'fu3010d3_count'),
 (643791, 'pp0qffd0_count'),
 (607691, 'ppz850d0_count'),
 (336789, 'ods000d0_count'),
 (226258, 'oli000d0_count'),
 (169935, 'htoautd0_count'),
 (158627, 'wcc006d0_count'),
 (120748, 'ppz700d0_count'),
 (44586, 'osr000d0_count'),
 (19294, 'olo000d0_count')]

"""

ALL = {
    "dkl010d0": {
        "shortname": "dkl010d0",
        "description_de": "Windrichtung; Tagesmittel",
        "description_fr": "Direction du vent; moyenne journalière",
        "description_it": "Direzione del vento; media giornaliera",
        "description_en": "Wind direction; daily mean",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "°",
    },
    "dkl010h0": {
        "shortname": "dkl010h0",
        "description_de": "Windrichtung; Stundenmittel",
        "description_fr": "Direction du vent; moyenne horaire",
        "description_it": "Direzione del vento; media oraria",
        "description_en": "Wind direction; hourly mean",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "°",
    },
    "dkl010z0": {
        "shortname": "dkl010z0",
        "description_de": "Windrichtung; Zehnminutenmittel",
        "description_fr": "Direction du vent; moyenne sur 10 minutes",
        "description_it": "Direzione del vento; media su 10'",
        "description_en": "Wind direction; ten minutes mean",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "°",
    },
    "erefaod0": {
        "shortname": "erefaod0",
        "description_de": "Referenzverdunstung nach FAO; Tagessumme",
        "description_fr": "Évaporation de réference de FAO; somme journalière",
        "description_it": "Evaporazione referenze di FAO; somma giornaliera",
        "description_en": "Reference evaporation from FAO; daily total",
        "group_de": "Verdunstung",
        "group_fr": "évaporation",
        "group_it": "evaporazione",
        "group_en": "evaporation",
        "datatype": "Float",
        "unit": "mm/d",
    },
    "erefaoh0": {
        "shortname": "erefaoh0",
        "description_de": "Referenzverdunstung nach FAO; Stundensumme",
        "description_fr": "Évaporation de réference de FAO; somme horaire",
        "description_it": "Evaporazione referenze di FAO; somma oraria",
        "description_en": "Reference evaporation from FAO; hourly total",
        "group_de": "Verdunstung",
        "group_fr": "évaporation",
        "group_it": "evaporazione",
        "group_en": "evaporation",
        "datatype": "Float",
        "unit": "mm/h",
    },
    "erefaom0": {
        "shortname": "erefaom0",
        "description_de": "Referenzverdunstung nach FAO; Monatssumme",
        "description_fr": "Évaporation de réference de FAO; somme mensuelle",
        "description_it": "Evaporazione referenze di FAO; somma mensile",
        "description_en": "Reference evaporation from FAO; monthly total",
        "group_de": "Verdunstung",
        "group_fr": "évaporation",
        "group_it": "evaporazione",
        "group_en": "evaporation",
        "datatype": "Float",
        "unit": "mm/d",
    },
    "erefaoy0": {
        "shortname": "erefaoy0",
        "description_de": "Referenzverdunstung nach FAO; Jahressumme",
        "description_fr": "Évaporation de réference de FAO; somme journalière",
        "description_it": "Evaporazione referenze di FAO; somma annuale",
        "description_en": "Reference evaporation from FAO; annual total",
        "group_de": "Verdunstung",
        "group_fr": "évaporation",
        "group_it": "evaporazione",
        "group_en": "evaporation",
        "datatype": "Float",
        "unit": "mm/d",
    },
    "fkl010d0": {
        "shortname": "fkl010d0",
        "description_de": "Windgeschwindigkeit skalar; Tagesmittel in m/s",
        "description_fr": "Vitesse du vent scalaire; moyenne journalière en m/s",
        "description_it": "Velocità del vento scalare; media giornaliera in m/s",
        "description_en": "Wind speed scalar; daily mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010d1": {
        "shortname": "fkl010d1",
        "description_de": "Böenspitze (Sekundenböe); Tagesmaximum in m/s",
        "description_fr": "Rafale (intégration 1 s); maximum journalier en m/s",
        "description_it": "Raffica del vento (su un secondo); massima giornaliera in m/s",
        "description_en": "Gust peak (one second); daily maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010d3": {
        "shortname": "fkl010d3",
        "description_de": "Böenspitze (3-Sekundenböe); Tagesmaximum in m/s",
        "description_fr": "Rafale (intégration 3 s); maximum journalier en m/s",
        "description_it": "Raffica del vento (su tre secondi); massima giornaliera in m/s",
        "description_en": "Gust peak (three seconds); daily maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010h0": {
        "shortname": "fkl010h0",
        "description_de": "Windgeschwindigkeit skalar; Stundenmittel in m/s",
        "description_fr": "Vitesse du vent scalaire; moyenne horaire en m/s",
        "description_it": "Velocità del vento scalare; media oraria in m/s",
        "description_en": "Wind speed scalar; hourly mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010h1": {
        "shortname": "fkl010h1",
        "description_de": "Böenspitze (Sekundenböe); Stundenmaximum in m/s",
        "description_fr": "Rafale (intégration 1 s); maximum horaire en m/s",
        "description_it": "Raffica del vento (su un secondo); massima oraria in m/s",
        "description_en": "Gust peak (one second); hourly maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010h3": {
        "shortname": "fkl010h3",
        "description_de": "Böenspitze (3-Sekundenböe); Stundenmaximum in m/s",
        "description_fr": "Rafale (intégration 3 s); maximum horaire en m/s",
        "description_it": "Raffica del vento (su tre secondi); massima oraria in m/s",
        "description_en": "Gust peak (three seconds); hourly maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010m0": {
        "shortname": "fkl010m0",
        "description_de": "Windgeschwindigkeit skalar; Monatsmittel in m/s",
        "description_fr": "Vitesse du vent scalaire; moyenne mensuelle en m/s",
        "description_it": "Velocità del vento scalare; media mensile in m/s",
        "description_en": "Wind speed scalar; monthly mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010m1": {
        "shortname": "fkl010m1",
        "description_de": "Böenspitze (Sekundenböe); Monatsmaximum in m/s",
        "description_fr": "Rafale (intégration 1 s); maximum mensuel en m/s",
        "description_it": "Raffica del vento (su un secondo); massima mensile in m/s",
        "description_en": "Gust peak (one second); monthly maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010y0": {
        "shortname": "fkl010y0",
        "description_de": "Windgeschwindigkeit skalar; Jahresmittel in m/s",
        "description_fr": "Vitesse du vent scalaire; moyenne annuelle en m/s",
        "description_it": "Velocità del vento scalare; media annuale in m/s",
        "description_en": "Wind speed scalar; annual mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010y1": {
        "shortname": "fkl010y1",
        "description_de": "Böenspitze (Sekundenböe); Jahresmaximum in m/s",
        "description_fr": "Rafale (intégration 1 s); maximum annuel en m/s",
        "description_it": "Raffica del vento (su un secondo); massima annuale in m/s",
        "description_en": "Gust peak (one second); annual maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010z0": {
        "shortname": "fkl010z0",
        "description_de": "Windgeschwindigkeit skalar; Zehnminutenmittel in m/s",
        "description_fr": "Vitesse du vent scalaire; moyenne sur 10 minutes en m/s",
        "description_it": "Velocità del vento scalare; media su 10' in m/s",
        "description_en": "Wind speed scalar; ten minutes mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010z1": {
        "shortname": "fkl010z1",
        "description_de": "Böenspitze (Sekundenböe); Maximum in m/s",
        "description_fr": "Rafale (intégration 1 s); maximum en m/s",
        "description_it": "Raffica del vento (su un secondo); massima in m/s",
        "description_en": "Gust peak (one second); maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fkl010z3": {
        "shortname": "fkl010z3",
        "description_de": "Böenspitze (3-Sekundenböe); Maximum in m/s",
        "description_fr": "Rafale (intégration 3 s); maximum en m/s",
        "description_it": "Raffica del vento (su tre secondi); massima in m/s",
        "description_en": "Gust peak (three seconds); maximum in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fu3010d0": {
        "shortname": "fu3010d0",
        "description_de": "Windgeschwindigkeit skalar; Tagesmittel in km/h",
        "description_fr": "Vitesse du vent scalaire; moyenne journalière en km/h",
        "description_it": "Velocità del vento scalare; media giornaliera in km/h",
        "description_en": "Wind speed scalar; daily mean in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010d1": {
        "shortname": "fu3010d1",
        "description_de": "Böenspitze (Sekundenböe); Tagesmaximum in km/h",
        "description_fr": "Rafale (intégration 1 s); maximum journalier en km/h",
        "description_it": "Raffica del vento (su un secondo); massima giornaliera in km/h",
        "description_en": "Gust peak (one second); daily maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010d3": {
        "shortname": "fu3010d3",
        "description_de": "Böenspitze (3-Sekundenböe); Tagesmaximum in km/h",
        "description_fr": "Rafale (intégration 3 s); maximum journalier en km/h",
        "description_it": "Raffica del vento (su tre secondi); massima giornaliera in km/h",
        "description_en": "Gust peak (three seconds); daily maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010h0": {
        "shortname": "fu3010h0",
        "description_de": "Windgeschwindigkeit skalar; Stundenmittel in km/h",
        "description_fr": "Vitesse du vent scalaire; moyenne horaire en km/h",
        "description_it": "Velocità del vento scalare; media oraria in km/h",
        "description_en": "Wind speed scalar; hourly mean in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010h1": {
        "shortname": "fu3010h1",
        "description_de": "Böenspitze (Sekundenböe); Stundenmaximum in km/h",
        "description_fr": "Rafale (intégration 1 s); maximum horaire en km/h",
        "description_it": "Raffica del vento (su un secondo); massima oraria in km/h",
        "description_en": "Gust peak (one second); hourly maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010h3": {
        "shortname": "fu3010h3",
        "description_de": "Böenspitze (3-Sekundenböe); Stundenmaximum in km/h",
        "description_fr": "Rafale (intégration 3 s); maximum horaire en km/h",
        "description_it": "Raffica del vento (su tre secondi); massima oraria in km/h",
        "description_en": "Gust peak (three seconds); hourly maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010m0": {
        "shortname": "fu3010m0",
        "description_de": "Windgeschwindigkeit skalar; Monatsmittel in km/h",
        "description_fr": "Vitesse du vent scalaire; moyenne mensuelle en km/h",
        "description_it": "Velocità del vento scalare; media mensile in km/h",
        "description_en": "Wind speed scalar; monthly mean in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010m1": {
        "shortname": "fu3010m1",
        "description_de": "Böenspitze (Sekundenböe); Monatsmaximum in km/h",
        "description_fr": "Rafale (intégration 1 s); maximum mensuel en km/h",
        "description_it": "Raffica del vento (su un secondo); massima mensile in km/h",
        "description_en": "Gust peak (one second); monthly maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010y0": {
        "shortname": "fu3010y0",
        "description_de": "Windgeschwindigkeit skalar; Jahresmittel in km/h",
        "description_fr": "Vitesse du vent scalaire; moyenne annuelle en km/h",
        "description_it": "Velocità del vento scalare; media annuale in km/h",
        "description_en": "Wind speed scalar; annual mean in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010y1": {
        "shortname": "fu3010y1",
        "description_de": "Böenspitze (Sekundenböe); Jahresmaximum in km/h",
        "description_fr": "Rafale (intégration 1 s); maximum annuel en km/h",
        "description_it": "Raffica del vento (su un secondo); massima annuale in km/h",
        "description_en": "Gust peak (one second); annual maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010z0": {
        "shortname": "fu3010z0",
        "description_de": "Windgeschwindigkeit; Zehnminutenmittel in km/h",
        "description_fr": "Vitesse du vent; moyenne sur 10 minutes en km/h",
        "description_it": "Velocità del vento; media su 10' in km/h",
        "description_en": "Wind speed; ten minutes mean in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010z1": {
        "shortname": "fu3010z1",
        "description_de": "Böenspitze (Sekundenböe); Maximum in km/h",
        "description_fr": "Rafale (intégration 1 s); maximum en km/h",
        "description_it": "Raffica del vento (su un secondo); massima in km/h",
        "description_en": "Gust peak (one second); maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fu3010z3": {
        "shortname": "fu3010z3",
        "description_de": "Böenspitze (3-Sekundenböe); Maximum in km/h",
        "description_fr": "Rafale (intégration 3 s); maximum en km/h",
        "description_it": "Raffica del vento (su tre secondi); massima in km/h",
        "description_en": "Gust peak (three seconds); maximum in km/h",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "km/h",
    },
    "fve010h0": {
        "shortname": "fve010h0",
        "description_de": "Windgeschwindigkeit vektoriell; Stundenmittel in m/s",
        "description_fr": "Vitesse du vent vectorielle; moyenne horaire en m/s",
        "description_it": "Velocità del vento vettoriale; media oraria in m/s",
        "description_en": "Wind speed vectorial; hourly mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "fve010z0": {
        "shortname": "fve010z0",
        "description_de": "Windgeschwindigkeit vektoriell; Zehnminutenmittel in m/s",
        "description_fr": "Vitesse du vent vectorielle; moyenne sur 10 minutes en m/s",
        "description_it": "Velocità del vento vettoriale; media su 10' in m/s",
        "description_en": "Wind speed vectoriel; ten minutes mean in m/s",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Float",
        "unit": "m/s",
    },
    "gre000d0": {
        "shortname": "gre000d0",
        "description_de": "Globalstrahlung; Tagesmittel",
        "description_fr": "Rayonnement global; moyenne journalière",
        "description_it": "Radiazione globale; media giornaliera",
        "description_en": "Global radiation; daily mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "gre000h0": {
        "shortname": "gre000h0",
        "description_de": "Globalstrahlung; Stundenmittel",
        "description_fr": "Rayonnement global; moyenne horaire",
        "description_it": "Radiazione globale; media oraria",
        "description_en": "Global radiation; hourly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "gre000m0": {
        "shortname": "gre000m0",
        "description_de": "Globalstrahlung; Monatsmittel",
        "description_fr": "Rayonnement global; moyenne mensuelle",
        "description_it": "Radiazione globale; media mensile",
        "description_en": "Global radiation; monthly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "gre000y0": {
        "shortname": "gre000y0",
        "description_de": "Globalstrahlung; Jahresmittel",
        "description_fr": "Rayonnement global; moyenne annuelle",
        "description_it": "Radiazione globale; media annuale",
        "description_en": "Global radiation; annual mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "gre000z0": {
        "shortname": "gre000z0",
        "description_de": "Globalstrahlung; Zehnminutenmittel",
        "description_fr": "Rayonnement global; moyenne sur 10 minutes",
        "description_it": "Radiazione globale; media su 10'",
        "description_en": "Global radiation; ten minutes mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "htoautd0": {
        "shortname": "htoautd0",
        "description_de": "Schneehöhe (automatisch gemessen); Morgenmessung von 6 UTC",
        "description_fr": "Hauteur de neige (mesurée automatiquement); mesure matinale de 6 UTC",
        "description_it": "Altezza del manto nevoso (misurazione automatica); misura delle 6 UTC",
        "description_en": "Snow depth (automatic measurement); morning measurement at 6 UTC",
        "group_de": "Schnee",
        "group_fr": "neige",
        "group_it": "neve",
        "group_en": "snow",
        "datatype": "Integer",
        "unit": "cm",
    },
    "htoauths": {
        "shortname": "htoauths",
        "description_de": "Schneehöhe (automatisch gemessen); stündlicher Momentanwert",
        "description_fr": "Hauteur de neige (mesurée automatiquement); valeur instantanée horaire",
        "description_it": "Altezza del manto nevoso (misurazione automatica); valore momentaneo orario",
        "description_en": "Snow depth (automatic measurement); hourly current value",
        "group_de": "Schnee",
        "group_fr": "neige",
        "group_it": "neve",
        "group_en": "snow",
        "datatype": "Integer",
        "unit": "cm",
    },
    "htoauts0": {
        "shortname": "htoauts0",
        "description_de": "Schneehöhe (automatisch gemessen); Momentanwert",
        "description_fr": "Hauteur de neige (mesurée automatiquement); valeur instantanée",
        "description_it": "Altezza del manto nevoso (misurazione automatica); valore momentaneo",
        "description_en": "Snow depth (automatic measurement); current value",
        "group_de": "Schnee",
        "group_fr": "neige",
        "group_it": "neve",
        "group_en": "snow",
        "datatype": "Integer",
        "unit": "cm",
    },
    "ods000d0": {
        "shortname": "ods000d0",
        "description_de": "Diffusstrahlung; Tagesmittel",
        "description_fr": "Rayonnement diffus; moyenne journalière",
        "description_it": "Radiazione diffusa; media giornaliera",
        "description_en": "Diffuse radiation; daily mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "ods000h0": {
        "shortname": "ods000h0",
        "description_de": "Diffusstrahlung; Stundenmittel",
        "description_fr": "Rayonnement diffus; moyenne horaire",
        "description_it": "Radiazione diffusa; media oraria",
        "description_en": "Diffuse radiation; hourly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "ods000z0": {
        "shortname": "ods000z0",
        "description_de": "Diffusstrahlung; Zehnminutenmittel",
        "description_fr": "Rayonnement diffus; moyenne sur 10 minutes",
        "description_it": "Radiazione diffusa; media su 10'",
        "description_en": "Diffuse radiation; ten minutes mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "oli000d0": {
        "shortname": "oli000d0",
        "description_de": "Langwellige Einstrahlung; Tagesmittel",
        "description_fr": "Irradiation par onde longue; moyenne journalière",
        "description_it": "Radiazione a onda lunga in ingresso; media giornaliera",
        "description_en": "Longwave incoming radiation; daily mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "oli000h0": {
        "shortname": "oli000h0",
        "description_de": "Langwellige Einstrahlung; Stundenmittel",
        "description_fr": "Irradiation par onde longue; moyenne horaire",
        "description_it": "Radiazione a onda lunga in ingresso; media oraria",
        "description_en": "Longwave incoming radiation; hourly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "oli000m0": {
        "shortname": "oli000m0",
        "description_de": "Langwellige Einstrahlung; Monatsmittel",
        "description_fr": "Irradiation par onde longue; moyenne mensuelle",
        "description_it": "Radiazione a onda lunga in ingresso; media mensile",
        "description_en": "Longwave incoming radiation; monthly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "oli000y0": {
        "shortname": "oli000y0",
        "description_de": "Langwellige Einstrahlung; Jahresmittel",
        "description_fr": "Irradiation par onde longue; moyenne annuelle",
        "description_it": "Radiazione a onda lunga in ingresso; media annuale",
        "description_en": "Longwave incoming radiation; annual mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "oli000z0": {
        "shortname": "oli000z0",
        "description_de": "Langwellige Einstrahlung; Zehnminutenmittel",
        "description_fr": "Irradiation par onde longue; moyenne sur 10 minutes",
        "description_it": "Radiazione a onda lunga in ingresso; media su 10'",
        "description_en": "Longwave incoming radiation; ten minutes mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "olo000d0": {
        "shortname": "olo000d0",
        "description_de": "Langwellige Ausstrahlung; Tagesmittel",
        "description_fr": "Rayonnement par onde longue; moyenne journalière",
        "description_it": "Radiazione a onda lunga in uscita; media giornaliera",
        "description_en": "Longwave outgoing radiation; daily mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "olo000h0": {
        "shortname": "olo000h0",
        "description_de": "Langwellige Ausstrahlung; Stundenmittel",
        "description_fr": "Rayonnement par onde longue; moyenne horaire",
        "description_it": "Radiazione a onda lunga in uscita; media oraria",
        "description_en": "Longwave outgoing radiation; hourly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "olo000m0": {
        "shortname": "olo000m0",
        "description_de": "Langwellige Ausstrahlung; Monatsmittel",
        "description_fr": "Rayonnement par onde longue; moyenne mensuelle",
        "description_it": "Radiazione a onda lunga in uscita; media mensile",
        "description_en": "Longwave outgoing radiation; monthly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "olo000y0": {
        "shortname": "olo000y0",
        "description_de": "Langwellige Ausstrahlung; Jahresmittel",
        "description_fr": "Rayonnement par onde longue; moyenne annuelle",
        "description_it": "Radiazione a onda lunga in uscita; media annuale",
        "description_en": "Longwave outgoing radiation; yearly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "olo000z0": {
        "shortname": "olo000z0",
        "description_de": "Langwellige Ausstrahlung; Zehnminutenmittel",
        "description_fr": "Rayonnement par onde longue; moyenne sur 10 minutes",
        "description_it": "Radiazione a onda lunga in uscita; media su 10'",
        "description_en": "Longwave outgoing radiation; ten minute mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "osr000d0": {
        "shortname": "osr000d0",
        "description_de": "Kurzwellig reflektierte Strahlung; Tagesmittel",
        "description_fr": "Rayonnement reflété par onde courte; moyenne journalière",
        "description_it": "Radiazione a onda corta rilflessa; media giornaliera",
        "description_en": "Shortwave reflected radiation; daily mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "osr000h0": {
        "shortname": "osr000h0",
        "description_de": "Kurzwellig reflektierte Strahlung; Stundenmittel",
        "description_fr": "Rayonnement reflété par onde courte; moyenne horaire",
        "description_it": "Radiazione a onda corta rilflessa; media oraria",
        "description_en": "Shortwave reflected radiation; hourly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "osr000m0": {
        "shortname": "osr000m0",
        "description_de": "Kurzwellig reflektierte Strahlung; Monatsmittel",
        "description_fr": "Rayonnement reflété par onde courte; moyenne mensuelle",
        "description_it": "Radiazione a onda corta rilflessa; media mensile",
        "description_en": "Shortwave reflected radiation; monthly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "osr000y0": {
        "shortname": "osr000y0",
        "description_de": "Kurzwellig reflektierte Strahlung; Jahresmittel",
        "description_fr": "Rayonnement reflété par onde courte; moyenne annuelle",
        "description_it": "Radiazione a onda corta rilflessa; media annuale",
        "description_en": "Shortwave reflected radiation; yearly mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "osr000z0": {
        "shortname": "osr000z0",
        "description_de": "Kurzwellig reflektierte Strahlung; Zehnminutenmittel",
        "description_fr": "Rayonnement reflété par onde courte; moyenne sur 10 minutes",
        "description_it": "Radiazione a onda corta rilflessa; media su 10'",
        "description_en": "Shortwave reflected radiation; ten minute mean",
        "group_de": "Strahlung",
        "group_fr": "rayonnement",
        "group_it": "radiazione",
        "group_en": "radiation",
        "datatype": "Integer",
        "unit": "W/m²",
    },
    "pp0qffd0": {
        "shortname": "pp0qffd0",
        "description_de": "Luftdruck reduziert auf Meeresniveau (QFF); Tagesmittel",
        "description_fr": "Pression atmosphérique réduite au niveau de la mer (QFF); moyenne journalière",
        "description_it": "Pressione ridotta al livello del mare (QFF); media giornaliera",
        "description_en": "Pressure reduced to sea level (QFF); daily mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qffh0": {
        "shortname": "pp0qffh0",
        "description_de": "Luftdruck reduziert auf Meeresniveau (QFF); Stundenmittel",
        "description_fr": "Pression atmosphérique réduite au niveau de la mer (QFF); moyenne horaire",
        "description_it": "Pressione ridotta al livello del mare (QFF); media oraria",
        "description_en": "Pressure reduced to sea level (QFF); hourly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qffm0": {
        "shortname": "pp0qffm0",
        "description_de": "Luftdruck reduziert auf Meeresniveau (QFF); Monatsmittel",
        "description_fr": "Pression atmosphérique réduite au niveau de la mer (QFF); moyenne mensuelle",
        "description_it": "Pressione ridotta al livello del mare (QFF); media mensile",
        "description_en": "Pressure reduced to sea level (QFF); monthly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qffs0": {
        "shortname": "pp0qffs0",
        "description_de": "Luftdruck reduziert auf Meeresniveau (QFF); Momentanwert",
        "description_fr": "Pression atmosphérique réduite au niveau de la mer (QFF); valeur instantanée",
        "description_it": "Pressione ridotta al livello del mare (QFF); valore momentaneo",
        "description_en": "Pressure reduced to sea level (QFF); current value",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qffy0": {
        "shortname": "pp0qffy0",
        "description_de": "Luftdruck reduziert auf Meeresniveau (QFF); Jahresmittel",
        "description_fr": "Pression atmosphérique réduite au niveau de la mer (QFF); moyenne annuelle",
        "description_it": "Pressione ridotta al livello del mare (QFF); media annuale",
        "description_en": "Pressure reduced to sea level (QFF); annual mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qnhd0": {
        "shortname": "pp0qnhd0",
        "description_de": "Luftdruck reduziert auf Meeresniveau mit Standardatmosphäre (QNH); Tagesmittel",
        "description_fr": "Pression atmosphérique réduite avec l'atmosphère standard (QNH); moyenne journalière",
        "description_it": "Pressione ridotta secondo l'atmosfero standard (QNH); media giornaliera",
        "description_en": "Pressure reduced to sea level according to standard atmosphere (QNH); daily mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qnhh0": {
        "shortname": "pp0qnhh0",
        "description_de": "Luftdruck reduziert auf Meeresniveau mit Standardatmosphäre (QNH); Stundenmittel",
        "description_fr": "Pression atmosphérique réduite avec l'atmosphère standard (QNH); moyenne horaire",
        "description_it": "Pressione ridotta secondo l'atmosfero standard (QNH); media oraria",
        "description_en": "Pressure reduced to sea level according to standard atmosphere (QNH); hourly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qnhm0": {
        "shortname": "pp0qnhm0",
        "description_de": "Luftdruck reduziert auf Meeresniveau mit Standardatmosphäre (QNH); Monatsmittel",
        "description_fr": "Pression atmosphérique réduite avec l'atmosphère standard (QNH); moyenne mensuelle",
        "description_it": "Pressione ridotta secondo l'atmosfero standard (QNH); media mensile",
        "description_en": "Pressure reduced to sea level according to standard atmosphere (QNH); monthly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qnhs0": {
        "shortname": "pp0qnhs0",
        "description_de": "Luftdruck reduziert auf Meeresniveau mit Standardatmosphäre (QNH); Momentanwert",
        "description_fr": "Pression atmosphérique réduite avec l'atmosphère standard (QNH); valeur instantanée",
        "description_it": "Pressione ridotta secondo l'atmosfero standard (QNH); valore momentano",
        "description_en": "Pressure reduced to sea level according to standard atmosphere (QNH); current value",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pp0qnhy0": {
        "shortname": "pp0qnhy0",
        "description_de": "Luftdruck reduziert auf Meeresniveau mit Standardatmosphäre (QNH); Jahresmittel",
        "description_fr": "Pression atmosphérique réduite avec l'atmosphère standard (QNH); moyenne annuelle",
        "description_it": "Pressione ridotta secondo l'atmosfero standard (QNH); media annuale",
        "description_en": "Pressure reduced to sea level according to standard atmosphere (QNH); annual mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "ppz700d0": {
        "shortname": "ppz700d0",
        "description_de": "Geopotentielle Höhe der 700 hPa-Fläche; Tagesmittel",
        "description_fr": "Altitude géopotentielle de la surface de 700 hPa; moyenne journalière",
        "description_it": "Altitudine geopotenziale del livello di 700 hPa; media giornaliera",
        "description_en": "Geopotential height of the 700 hPA level; daily mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz700h0": {
        "shortname": "ppz700h0",
        "description_de": "Geopotentielle Höhe der 700 hPa-Fläche; Stundenmittel",
        "description_fr": "Altitude géopotentielle de la surface de 700 hPa; moyenne horaire",
        "description_it": "Altitudine geopotenziale del livello di 700 hPa; media oraria",
        "description_en": "Geopotential height of the 700 hPA level; hourly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz700m0": {
        "shortname": "ppz700m0",
        "description_de": "Geopotentielle Höhe der 700 hPa-Fläche; Monatsmittel",
        "description_fr": "Altitude géopotentielle de la surface de 700 hPa; moyenne mensuelle",
        "description_it": "Altitudine geopotenziale del livello di 700 hPa; media mensile",
        "description_en": "Geopotential height of the 700 hPA level; monthly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz700s0": {
        "shortname": "ppz700s0",
        "description_de": "Geopotentielle Höhe der 700 hPa-Fläche; Momentanwert",
        "description_fr": "Altitude géopotentielle de la surface de 700 hPa; valeur instantanée",
        "description_it": "Altitudine geopotenziale del livello di 700 hPa; valore momentaneo",
        "description_en": "Geopotential height of the 700 hPA level; current value",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz700y0": {
        "shortname": "ppz700y0",
        "description_de": "Geopotentielle Höhe der 700 hPa-Fläche; Jahresmittel",
        "description_fr": "Altitude géopotentielle de la surface de 700 hPa; moyenne annuelle",
        "description_it": "Altitudine geopotenziale del livello di 700 hPa; media annuale",
        "description_en": "Geopotential height of the 700 hPA level; yearly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz850d0": {
        "shortname": "ppz850d0",
        "description_de": "Geopotentielle Höhe der 850 hPa-Fläche; Tagesmittel",
        "description_fr": "Altitude géopotentielle de la surface de 850 hPa; moyenne journalière",
        "description_it": "Altitudine geopotenziale del livello di 850 hPa; media giornaliera",
        "description_en": "Geopotential height of the 850 hPA level; daily mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz850h0": {
        "shortname": "ppz850h0",
        "description_de": "Geopotentielle Höhe der 850 hPa-Fläche; Stundenmittel",
        "description_fr": "Altitude géopotentielle de la surface de 850 hPa; moyenne horaire",
        "description_it": "Altitudine geopotenziale del livello di 850 hPa; media oraria",
        "description_en": "Geopotential height of the 850 hPA level; hourly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz850m0": {
        "shortname": "ppz850m0",
        "description_de": "Geopotentielle Höhe der 850 hPa-Fläche; Monatsmittel",
        "description_fr": "Altitude géopotentielle de la surface de 850 hPa; moyenne mensuelle",
        "description_it": "Altitudine geopotenziale del livello di 850 hPa; media mensile",
        "description_en": "Geopotential height of the 850 hPA level; monthly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz850s0": {
        "shortname": "ppz850s0",
        "description_de": "Geopotentielle Höhe der 850 hPa-Fläche; Momentanwert",
        "description_fr": "Altitude géopotentielle de la surface de 850 hPa; valeur instantanée",
        "description_it": "Altitudine geopotenziale del livello di 850 hPa; valore momentaneo",
        "description_en": "Geopotential height of the 850 hPA level; current value",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "ppz850y0": {
        "shortname": "ppz850y0",
        "description_de": "Geopotentielle Höhe der 850 hPa-Fläche; Jahresmittel",
        "description_fr": "Altitude géopotentielle de la surface de 850 hPa; moyenne annuelle",
        "description_it": "Altitudine geopotenziale del livello di 850 hPa; media annuale",
        "description_en": "Geopotential height of the 850 hPA level; yearly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "gpm",
    },
    "prestad0": {
        "shortname": "prestad0",
        "description_de": "Luftdruck auf Barometerhöhe (QFE); Tagesmittel",
        "description_fr": "Pression atmosphérique à l'altitude du baromètre (QFE); moyenne journalière",
        "description_it": "Pressione all'altitudine barometrica (QFE); media giornaliera",
        "description_en": "Atmospheric pressure at barometric altitude (QFE); daily mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "prestah0": {
        "shortname": "prestah0",
        "description_de": "Luftdruck auf Barometerhöhe (QFE); Stundenmittel",
        "description_fr": "Pression atmosphérique à l'altitude du baromètre (QFE); moyenne horaire",
        "description_it": "Pressione all'altitudine barometrica (QFE); media oraria",
        "description_en": "Atmospheric pressure at barometric altitude (QFE); hourly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "prestam0": {
        "shortname": "prestam0",
        "description_de": "Luftdruck auf Barometerhöhe (QFE); Monatsmittel",
        "description_fr": "Pression atmosphérique à l'altitude du baromètre (QFE); moyenne mensuelle",
        "description_it": "Pressione all'altitudine barometrica (QFE); media mensile",
        "description_en": "Atmospheric pressure at barometric altitude (QFE); monthly mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "prestas0": {
        "shortname": "prestas0",
        "description_de": "Luftdruck auf Barometerhöhe (QFE); Momentanwert",
        "description_fr": "Pression atmosphérique à l'altitude du baromètre (QFE); valeur instantanée",
        "description_it": "Pressione all'altitudine barometrica (QFE); valore momentaneo",
        "description_en": "Atmospheric pressure at barometric altitude (QFE); current value",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "prestay0": {
        "shortname": "prestay0",
        "description_de": "Luftdruck auf Barometerhöhe (QFE); Jahresmittel",
        "description_fr": "Pression atmosphérique à l'altitude du baromètre (QFE); moyenne annuelle",
        "description_it": "Pressione all'altitudine barometrica (QFE); media annuale",
        "description_en": "Atmospheric pressure at barometric altitude (QFE); annual mean",
        "group_de": "Druck",
        "group_fr": "pression",
        "group_it": "pressione",
        "group_en": "pressure",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pva200d0": {
        "shortname": "pva200d0",
        "description_de": "Dampfdruck 2 m über Boden; Tagesmittel",
        "description_fr": "Pression de vapeur à 2 m du sol; moyenne journalière",
        "description_it": "Pressione del vapore acqueo a 2 m dal suolo; media giornaliera",
        "description_en": "Vapour pressure 2 m above ground; daily mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pva200h0": {
        "shortname": "pva200h0",
        "description_de": "Dampfdruck 2 m über Boden; Stundenmittel",
        "description_fr": "Pression de vapeur à 2 m du sol; moyenne horaire",
        "description_it": "Pressione del vapore acqueo a 2 m dal suolo; media oraria",
        "description_en": "Vapour pressure 2 m above ground; hourly mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pva200m0": {
        "shortname": "pva200m0",
        "description_de": "Dampfdruck 2 m über Boden; Monatsmittel",
        "description_fr": "Pression de vapeur à 2 m du sol; moyenne mensuelle",
        "description_it": "Pressione del vapore acqueo a 2 m dal suolo; media mensile",
        "description_en": "Vapour pressure 2 m above ground; monthly mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pva200s0": {
        "shortname": "pva200s0",
        "description_de": "Dampfdruck 2 m über Boden; Momentanwert",
        "description_fr": "Pression de vapeur à 2 m du sol; valeur instantanée",
        "description_it": "Pressione del vapore acqueo a 2 m dal suolo; valore momentaneo",
        "description_en": "Vapour pressure 2 m above ground; current value",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "hPa",
    },
    "pva200y0": {
        "shortname": "pva200y0",
        "description_de": "Dampfdruck 2 m über Boden; Jahresmittel",
        "description_fr": "Pression de vapeur à 2 m du sol; moyenne annuelle",
        "description_it": "Pressione del vapore acqueo a 2 m dal suolo; media annuale",
        "description_en": "Vapour pressure 2 m above ground; annual mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "hPa",
    },
    "rka150d0": {
        "shortname": "rka150d0",
        "description_de": "Niederschlag; Tagessumme 0 UTC - 0 UTC",
        "description_fr": "Précipitations; somme du jour 0 UTC - 0 UTC",
        "description_it": "Precipitazioni; somma giornaliera 0 UTC - 0 UTC",
        "description_en": "Precipitation; daily total 0 UTC - 0 UTC",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rre150d0": {
        "shortname": "rre150d0",
        "description_de": "Niederschlag; Tagessumme 6 UTC - 6 UTC Folgetag",
        "description_fr": "Précipitations; somme journalière 6 UTC - 6 UTC du jour suivant",
        "description_it": "Precipitazioni; somma giornaliera 6 UTC - 6 UTC del giorno seguente",
        "description_en": "Precipitation; daily total 6 UTC - 6 UTC following day",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rre150h0": {
        "shortname": "rre150h0",
        "description_de": "Niederschlag; Stundensumme",
        "description_fr": "Précipitations; somme horaire",
        "description_it": "Precipitazioni; somma oraria",
        "description_en": "Precipitation; hourly total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rre150m0": {
        "shortname": "rre150m0",
        "description_de": "Niederschlag; Monatssumme",
        "description_fr": "Précipitations; somme mensuelle",
        "description_it": "Precipitazioni; somma mensile",
        "description_en": "Precipitation; monthly total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rre150y0": {
        "shortname": "rre150y0",
        "description_de": "Niederschlag; Jahressumme",
        "description_fr": "Précipitations; somme annuelle",
        "description_it": "Precipitazioni; somma annuale",
        "description_en": "Precipitation; annual total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rre150z0": {
        "shortname": "rre150z0",
        "description_de": "Niederschlag; Zehnminutensumme",
        "description_fr": "Précipitations; sommation sur 10 minutes",
        "description_it": "Precipitazioni; somma su 10'",
        "description_en": "Precipitation; ten minutes total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rreetsd0": {
        "shortname": "rreetsd0",
        "description_de": "Wassereintrag (Wasserbilanz, R-ETS); Tagessumme",
        "description_fr": "Apport d'eau (bilan hydrique, R-ETS); somme journalière",
        "description_it": "Registrazione idrica (bilancio idrico, R-ETS); somma giornaliera",
        "description_en": "Hydrologic registration (hydrologic balance, R-ETS); daily total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rreetsm0": {
        "shortname": "rreetsm0",
        "description_de": "Wassereintrag (Wasserbilanz, R-ETS); Monatssumme",
        "description_fr": "Apport d'eau (bilan hydrique, R-ETS); somme mensuelle",
        "description_it": "Registrazione idrica (bilancio idrico, R-ETS); somma mensile",
        "description_en": "Hydrologic registration (hydrologic balance, R-ETS); monthly total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "rreetsy0": {
        "shortname": "rreetsy0",
        "description_de": "Wassereintrag (Wasserbilanz, R-ETS); Jahressumme",
        "description_fr": "Apport d'eau (bilan hydrique, R-ETS); somme annuelle",
        "description_it": "Registrazione idrica (bilancio idrico, R-ETS); somma annuale",
        "description_en": "Hydrologic registration (hydrologic balance, R-ETS); annual total",
        "group_de": "Niederschlag",
        "group_fr": "précipitations",
        "group_it": "precipitazioni",
        "group_en": "precipitation",
        "datatype": "Float",
        "unit": "mm",
    },
    "sre000d0": {
        "shortname": "sre000d0",
        "description_de": "Sonnenscheindauer; Tagessumme",
        "description_fr": "Durée d'ensoleillement; somme journalière",
        "description_it": "Soleggiamento; somma giornaliera",
        "description_en": "Sunshine duration; daily total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "min",
    },
    "sre000h0": {
        "shortname": "sre000h0",
        "description_de": "Sonnenscheindauer; Stundensumme",
        "description_fr": "Durée d'ensoleillement; somme horaire",
        "description_it": "Soleggiamento; somma oraria",
        "description_en": "Sunshine duration; hourly total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "min",
    },
    "sre000m0": {
        "shortname": "sre000m0",
        "description_de": "Sonnenscheindauer; Monatssumme",
        "description_fr": "Durée d'ensoleillement; somme mensuelle",
        "description_it": "Soleggiamento; somma mensile",
        "description_en": "Sunshine duration; monthly total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "min",
    },
    "sre000y0": {
        "shortname": "sre000y0",
        "description_de": "Sonnenscheindauer; Jahressumme",
        "description_fr": "Durée d'ensoleillement; somme annuelle",
        "description_it": "Soleggiamento; somma annuale",
        "description_en": "Sunshine duration; annual total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "min",
    },
    "sre000z0": {
        "shortname": "sre000z0",
        "description_de": "Sonnenscheindauer; Zehnminutensumme",
        "description_fr": "Durée d'ensoleillement; sommation sur 10 minutes",
        "description_it": "Soleggiamento; somma su 10'",
        "description_en": "Sunshine duration; ten minutes total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "min",
    },
    "sremaxdv": {
        "shortname": "sremaxdv",
        "description_de": "Sonnenscheindauer; relativ zur absolut möglichen Tagessumme",
        "description_fr": "Durée d'ensoleillement; relativement à la somme journalière maximale possible",
        "description_it": "Soleggiamento; rispetto al massimo giornaliero possibile",
        "description_en": "Sunshine duration; in relation to absolute daily total",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "%",
    },
    "sremaxmv": {
        "shortname": "sremaxmv",
        "description_de": "Sonnenscheindauer; Verhältnis der Monatssumme zur maximal Möglichen",
        "description_fr": "Durée d'ensoleillement; rapport de la somme mensuelle au maximum possible",
        "description_it": "Soleggiamento; somma mensile rispetto al massimo possibile",
        "description_en": "Sunshine duration; relation of the monthly total to the possible maximum",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "%",
    },
    "sremaxyv": {
        "shortname": "sremaxyv",
        "description_de": "Sonnenscheindauer; Verhältnis der Jahressumme zur maximal Möglichen",
        "description_fr": "Durée d'ensoleillement; rapport de la somme annuelle au maximum possible",
        "description_it": "Soleggiamento; somma annuale rispetto al massimo possibile",
        "description_en": "Sunshine duration; relation of the annual total to the possible maximum",
        "group_de": "Sonne",
        "group_fr": "ensoleillement",
        "group_it": "soleggiamento",
        "group_en": "sunshine",
        "datatype": "Integer",
        "unit": "%",
    },
    "tde200h0": {
        "shortname": "tde200h0",
        "description_de": "Taupunkt 2 m über Boden; Stundenmittel",
        "description_fr": "Point de rosée à 2 m du sol; moyenne horaire",
        "description_it": "Punto di rugiada a 2 m dal suolo; media oraria",
        "description_en": "Dew point 2 m above ground; hourly mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "°C",
    },
    "tde200s0": {
        "shortname": "tde200s0",
        "description_de": "Taupunkt 2 m über Boden; Momentanwert",
        "description_fr": "Point de rosée à 2 m du sol; valeur instantanée",
        "description_it": "Punto di rugiada a 2 m dal suolo; valore momentaneo",
        "description_en": "Dew point 2 m above ground; current value",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005d0": {
        "shortname": "tre005d0",
        "description_de": "Lufttemperatur 5 cm über Gras; Tagesmittel",
        "description_fr": "Température de l'air à 5 cm de l'herbe; moyenne journalière",
        "description_it": "Temperatura a 5 cm sull'erba; media giornaliera",
        "description_en": "Air temperature at 5 cm above grass; daily mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005dn": {
        "shortname": "tre005dn",
        "description_de": "Lufttemperatur 5 cm über Gras; Tagesminimum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; minimum journalier",
        "description_it": "Temperatura a 5 cm sull'erba; minima giornaliera",
        "description_en": "Air temperature at 5 cm above grass; daily minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005dx": {
        "shortname": "tre005dx",
        "description_de": "Lufttemperatur 5 cm über Gras; Tagesmaximum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; maximum journalier",
        "description_it": "Temperatura a 5 cm sull'erba; massima giornaliera",
        "description_en": "Air temperature at 5 cm above grass; daily maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005h0": {
        "shortname": "tre005h0",
        "description_de": "Lufttemperatur 5 cm über Gras; Stundenmittel",
        "description_fr": "Température de l'air à 5 cm de l'herbe; moyenne horaire",
        "description_it": "Temperatura a 5 cm sull'erba; media oraria",
        "description_en": "Air temperature at 5 cm above grass; hourly mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005hn": {
        "shortname": "tre005hn",
        "description_de": "Lufttemperatur 5 cm über Gras; Stundenminimum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; minimum horaire",
        "description_it": "Temperatura a 5 cm sull'erba; minima oraria",
        "description_en": "Air temperature at 5 cm above grass; hourly minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005m0": {
        "shortname": "tre005m0",
        "description_de": "Lufttemperatur 5 cm über Gras; Monatsmittel",
        "description_fr": "Température de l'air à 5 cm de l'herbe; moyenne mensuelle",
        "description_it": "Temperatura a 5 cm sull'erba; media mensile",
        "description_en": "Air temperature at 5 cm above grass; monthly mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005mn": {
        "shortname": "tre005mn",
        "description_de": "Lufttemperatur 5 cm über Gras; absolutes Monatsminimum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; minimum mensuel absolu",
        "description_it": "Temperatura a 5 cm sull'erba; minima mensile assoluta",
        "description_en": "Air temperature at 5 cm above grass; absolute monthly minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005mx": {
        "shortname": "tre005mx",
        "description_de": "Lufttemperatur 5 cm über Gras; absolutes Monatsmaximum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; maximum mensuel absolu",
        "description_it": "Temperatura a 5 cm sull'erba; massima mensile assoluta",
        "description_en": "Air temperature at 5 cm above grass; absolute monthly maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005s0": {
        "shortname": "tre005s0",
        "description_de": "Lufttemperatur 5 cm über Gras; Momentanwert",
        "description_fr": "Température de l'air à 5 cm de l'herbe; valeur instantanée",
        "description_it": "Temperatura a 5 cm sull'erba; valore momentaneo",
        "description_en": "Air temperature at 5 cm above grass; current value",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005y0": {
        "shortname": "tre005y0",
        "description_de": "Lufttemperatur 5 cm über Gras; Jahresmittel",
        "description_fr": "Température de l'air à 5 cm de l'herbe; moyenne annuelle",
        "description_it": "Temperatura a 5 cm sull'erba; media annuale",
        "description_en": "Air temperature at 5 cm above grass; annual mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005yn": {
        "shortname": "tre005yn",
        "description_de": "Lufttemperatur 5 cm über Gras; absolutes Jahresminimum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; minimum annuel absolu",
        "description_it": "Temperatura a 5 cm sull'erba; minima annuale assoluta",
        "description_en": "Air temperature at 5 cm above grass; absolute annual minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre005yx": {
        "shortname": "tre005yx",
        "description_de": "Lufttemperatur 5 cm über Gras; absolutes Jahresmaximum",
        "description_fr": "Température de l'air à 5 cm de l'herbe; maximum annuel absolu",
        "description_it": "Temperatura a 5 cm sull'erba; massima annuale assoluta",
        "description_en": "Air temperature at 5 cm above grass; absolute annual maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200d0": {
        "shortname": "tre200d0",
        "description_de": "Lufttemperatur 2 m über Boden; Tagesmittel",
        "description_fr": "Température de l'air à 2 m du sol; moyenne journalière",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; media giornaliera",
        "description_en": "Air temperature 2 m above ground; daily mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200dn": {
        "shortname": "tre200dn",
        "description_de": "Lufttemperatur 2 m über Boden; Tagesminimum",
        "description_fr": "Température de l'air à 2 m du sol; minimum journalier",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; minima giornaliera",
        "description_en": "Air temperature 2 m above ground; daily minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200dx": {
        "shortname": "tre200dx",
        "description_de": "Lufttemperatur 2 m über Boden; Tagesmaximum",
        "description_fr": "Température de l'air à 2 m du sol; maximum journalier",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; massima giornaliera",
        "description_en": "Air temperature 2 m above ground; daily maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200h0": {
        "shortname": "tre200h0",
        "description_de": "Lufttemperatur 2 m über Boden; Stundenmittel",
        "description_fr": "Température de l'air à 2 m du sol; moyenne horaire",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; media oraria",
        "description_en": "Air temperature 2 m above ground; hourly mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200hn": {
        "shortname": "tre200hn",
        "description_de": "Lufttemperatur 2 m über Boden; Stundenminimum",
        "description_fr": "Température de l'air à 2 m du sol; minimum horaire",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; minima oraria",
        "description_en": "Air temperature 2 m above ground; hourly minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200hx": {
        "shortname": "tre200hx",
        "description_de": "Lufttemperatur 2 m über Boden; Stundenmaximum",
        "description_fr": "Température de l'air à 2 m du sol; maximum horaire",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; massima oraria",
        "description_en": "Air temperature 2 m above ground; hourly maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200m0": {
        "shortname": "tre200m0",
        "description_de": "Lufttemperatur 2 m über Boden; Monatsmittel",
        "description_fr": "Température de l'air à 2 m du sol; moyenne mensuelle",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; media mensile",
        "description_en": "Air temperature 2 m above ground; monthly mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200mn": {
        "shortname": "tre200mn",
        "description_de": "Lufttemperatur 2 m über Boden; absolutes Monatsminimum",
        "description_fr": "Température de l'air à 2 m du sol; minimum mensuel absolu",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; minima mensile assoluta",
        "description_en": "Air temperature 2 m above ground; absolute monthly minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200mx": {
        "shortname": "tre200mx",
        "description_de": "Lufttemperatur 2 m über Boden; absolutes Monatsmaximum",
        "description_fr": "Température de l'air à 2 m du sol; maximum mensuel absolu",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; massima mensile assoluta",
        "description_en": "Air temperature 2 m above ground; absolute monthly maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200s0": {
        "shortname": "tre200s0",
        "description_de": "Lufttemperatur 2 m über Boden; Momentanwert",
        "description_fr": "Température de l'air à 2 m du sol; valeur instantanée",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; valore momentaneo",
        "description_en": "Air temperature 2 m above ground; current value",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200y0": {
        "shortname": "tre200y0",
        "description_de": "Lufttemperatur 2 m über Boden; Jahresmittel",
        "description_fr": "Température de l'air à 2 m du sol; moyenne annuelle",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; media annuale",
        "description_en": "Air temperature 2 m above ground; annual mean",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200yn": {
        "shortname": "tre200yn",
        "description_de": "Lufttemperatur 2 m über Boden; absolutes Jahresminimum",
        "description_fr": "Température de l'air à 2 m du sol; minimum annuel absolu",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; minima annuale assoluta",
        "description_en": "Air temperature 2 m above ground; absolute annual minimum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tre200yx": {
        "shortname": "tre200yx",
        "description_de": "Lufttemperatur 2 m über Boden; absolutes Jahresmaximum",
        "description_fr": "Température de l'air à 2 m du sol; maximum annuel absolu",
        "description_it": "Temperatura dell'aria a 2 m dal suolo; massima annuale assoluta",
        "description_en": "Air temperature 2 m above ground; absolute annual maximum",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "tresurs0": {
        "shortname": "tresurs0",
        "description_de": "Lufttemperatur Bodenoberfläche; Momentanwert",
        "description_fr": "Température de l'air à la surface du sol; valeur instantanée",
        "description_it": "Temperatura dell'aria al livello del suolo; valore momentaneo",
        "description_en": "Air temperature at surface; current value",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "ure200d0": {
        "shortname": "ure200d0",
        "description_de": "Relative Luftfeuchtigkeit 2 m über Boden; Tagesmittel",
        "description_fr": "Humidité de l'air relative à 2 m du sol; moyenne journalière",
        "description_it": "Umidità relativa dell'aria a 2 m dal suolo; media giornaliera",
        "description_en": "Relative air humidity 2 m above ground; daily mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "%",
    },
    "ure200h0": {
        "shortname": "ure200h0",
        "description_de": "Relative Luftfeuchtigkeit 2 m über Boden; Stundenmittel",
        "description_fr": "Humidité de l'air relative à 2 m du sol; moyenne horaire",
        "description_it": "Umidità relativa dell'aria a 2 m dal suolo; media oraria",
        "description_en": "Relative air humidity 2 m above ground; hourly mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "%",
    },
    "ure200m0": {
        "shortname": "ure200m0",
        "description_de": "Relative Luftfeuchtigkeit 2 m über Boden; Monatsmittel",
        "description_fr": "Humidité de l'air relative à 2 m du sol; moyenne mensuelle",
        "description_it": "Umidità relativa dell'aria a 2 m dal suolo; media mensile",
        "description_en": "Relative air humidity 2 m above ground; monthly mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "%",
    },
    "ure200s0": {
        "shortname": "ure200s0",
        "description_de": "Relative Luftfeuchtigkeit 2 m über Boden; Momentanwert",
        "description_fr": "Humidité de l'air relative à 2 m du sol; valeur instantanée",
        "description_it": "Umidità relativa dell'aria a 2 m dal suolo; valore momentaneo",
        "description_en": "Relative air humidity 2 m above ground; current value",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "%",
    },
    "ure200y0": {
        "shortname": "ure200y0",
        "description_de": "Relative Luftfeuchtigkeit 2 m über Boden; Jahresmittel",
        "description_fr": "Humidité de l'air relative à 2 m du sol; moyenne annuelle",
        "description_it": "Umidità relativa dell'aria a 2 m dal suolo; media annuale",
        "description_en": "Relative air humidity 2 m above ground; annual mean",
        "group_de": "Feuchte",
        "group_fr": "humidité",
        "group_it": "umidità",
        "group_en": "humidity",
        "datatype": "Float",
        "unit": "%",
    },
    "wcc006d0": {
        "shortname": "wcc006d0",
        "description_de": "Föhnindex, Tageswert",
        "description_fr": "Foehn index; valeur journalière",
        "description_it": "Indice di favonio; valore giornaliera",
        "description_en": "Foehn index; daily value",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "min",
    },
    "wcc006h0": {
        "shortname": "wcc006h0",
        "description_de": "Föhnindex; Stundenwert",
        "description_fr": "Foehn index; valeur horaire",
        "description_it": "Indice di favonio; valore oraria",
        "description_en": "Foehn index; hour value",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "min",
    },
    "wcc006s0": {
        "shortname": "wcc006s0",
        "description_de": "Föhnindex",
        "description_fr": "Foehn index",
        "description_it": "Indice di favonio",
        "description_en": "Foehn index",
        "group_de": "Wind",
        "group_fr": "vent",
        "group_it": "vento",
        "group_en": "wind",
        "datatype": "Integer",
        "unit": "Code",
    },
    "xcd000d0": {
        "shortname": "xcd000d0",
        "description_de": "Kühlgradzahl (CDD: Cooling Degree Day, nach USA)",
        "description_fr": "Jours de refroidissment (CDD)",
        "description_it": "Giorni di raffredamento (CDD)",
        "description_en": "Cooling Degree Day (CDD)",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xcd000m0": {
        "shortname": "xcd000m0",
        "description_de": "Kühlgradzahl (CDD nach USA); Monatssumme",
        "description_fr": "Jours de refroidissment (CDD); somme mensuelle",
        "description_it": "Giorni di raffredamento (CDD); totale mensile",
        "description_en": "Cooling Degree Day (CDD); monthly total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xcd000y0": {
        "shortname": "xcd000y0",
        "description_de": "Kühlgradzahl (CDD nach USA); Jahressumme",
        "description_fr": "Jours de refroidissment (CDD); somme annuelle",
        "description_it": "Giorni di raffredamento (CDD); somma annuale",
        "description_en": "Cooling Degree Day (CDD); annual total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xchills0": {
        "shortname": "xchills0",
        "description_de": "Chill Temperatur; Momentanwert",
        "description_fr": "Chill température; valeur instantanée",
        "description_it": "Temperatura fredda; valore momentaneo",
        "description_en": "Chill temperature; current value",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno000d0": {
        "shortname": "xno000d0",
        "description_de": "Heizgradzahl 12/20 (SIA: Heizgradtage)",
        "description_fr": "Degrés jours (HGT12/20)",
        "description_it": "Gradi riscaldamento (12/20)",
        "description_en": "Heating degrees (HGT12/20)",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno000m0": {
        "shortname": "xno000m0",
        "description_de": "Heizgradzahl 12/20 (SIA: Heizgradtage); Monatssumme",
        "description_fr": "Degrés jours (HGT12/20); somme mensuelle",
        "description_it": "Gradi riscaldamento (12/20); somma mensile",
        "description_en": "Heating degrees (HGT12/20); monthly total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno000y0": {
        "shortname": "xno000y0",
        "description_de": "Heizgradzahl 12/20 (SIA: Heizgradtage); Jahressumme",
        "description_fr": "Degrés jours (HGT12/20); somme annuelle",
        "description_it": "Gradi riscaldamento (12/20); somma annuale",
        "description_en": "Heating degrees (HGT12/20); annual total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno012d0": {
        "shortname": "xno012d0",
        "description_de": "Heizgradtage ATD12",
        "description_fr": "Degrés jours (ATD12/12)",
        "description_it": "Gradi riscaldamento (ATD12/12)",
        "description_en": "Heating degrees (ATD12/12)",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno012m0": {
        "shortname": "xno012m0",
        "description_de": "Heizgradtage ATD12; Monatssumme",
        "description_fr": "Degrés jours (ATD12/12); somme mensuelle",
        "description_it": "Gradi riscaldamento (ATD12/12); somma mensile",
        "description_en": "Heating degrees (ATD12/12); monthly total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
    "xno012y0": {
        "shortname": "xno012y0",
        "description_de": "Heizgradtage ATD12; Jahressumme",
        "description_fr": "Degrés jours (ATD12/12); somme annuelle",
        "description_it": "Gradi riscaldamento (ATD12/12); somma annuale",
        "description_en": "Heating degrees (ATD12/12); annual total",
        "group_de": "Temperatur",
        "group_fr": "température",
        "group_it": "temperatura",
        "group_en": "temperature",
        "datatype": "Float",
        "unit": "°C",
    },
}
